### ISSUE TITLE
(D) tRNAscan-SE (medium, needs A)

### ISSUE THREAD

**Issue by mrshu** [fmfi-genomika/genomikaMalGlo#4]
- Run software for finding tRNA genes (for comparison with annotation)
- Download software from http://lowelab.ucsc.edu/tRNAscan-SE/ (already installed on compbio servers as tRNAscan-SE command)
- Convert output by script rna/tRNAscan-SEtoBED.py on github
- trackDb.ra record:

```
track tRNAs
shortLabel tRNA Genes
longLabel Transfer RNA Genes Identified with tRNAscan-SE
group genes
visibility hide
color 0,20,150
type bed 12
nextItemButton on
priority 10
```

**Comment by mrshu** [comment]
@ViRPo anything I can help with here (so that we can close this)?

**Comment by virpo** [comment]
@mrshu it should be complete now :)

**Comment by mrshu** [comment]
@ViRPo very cool, thanks!

**Comment by bbrejova** [comment]
I have found a small problem with this track: it seems that the browser has built-in different behavior for tracks named tRNAs. If you click on a particular tRNA gene (e.g.  http://genomika.compbio.fmph.uniba.sk/cgi-bin/hgTracks?db=malGlo1&position=NW_001849856.1:157031-157115 ), you will get an automatically generated info page about this gene which uses columns of our bed file incorrectly, leading to nonsense. For example, anticodon should be GCC here, not 157030.

One way would be to parse tRNAscan-SE output differently, producing a BED file more similar to tRNA tracks in the UCSC genome browser http://genome-euro.ucsc.edu/cgi-bin/hgTables?db=hg38&hgta_group=genes&hgta_track=tRNAs&hgta_table=tRNAs&hgta_doSchema=describe+table+schema

However, I would suggest a simpler approach: rename the tRNAs track differently, e.g. only tRNA (drop tRNAs table from the database, load again to tRNA table, change trackDb.ra, make alpha,...)

**Comment by virpo** [comment]
I did as suggested

However, I didn't check what the parsed output looked like before these changes, so I don't know whether the output changed at all, but it seems OK to me

**Comment by bbrejova** [comment]
Looks good
