### ISSUE TITLE
(E) Augustus (slow, needs A)

### ISSUE THREAD

**Issue by mrshu** [fmfi-genomika/genomikaMalGlo#5]
- Run gene finder Augustus, create track with predicted genes (for comparison with annotation)
- Download and install software from http://bioinf.uni-greifswald.de/augustus/
  - Already installed on compbio servers
- Example of command line: `augustus --uniqueGeneId=true --species=ustilago_maydis genome.fa > augustus.gtf`
- ustilago_maydis is a related fungal species used for training parameters
- The result needs to be converted from gtf to genepred, by gtfToGenePred (at genomika server) with option -genePredExt
- If you name your track augustus, genome browser will recognize it automatically, no need to modify trackDb.ra

**Comment by mrshu** [comment]
@Zygro anything I can help with here (so that we can close this)?

**Comment by mrshu** [comment]
@Zygro Please let me know if I can help in any way to get this done.

Thanks!

**Comment by Zygro** [comment]
@mrshu I didn't get enough time to do this, but i should be able to do it this weekend

**Comment by Zygro** [comment]
I have the data, however I can't find where is the DB. MalSym wiki says that I should run `hgLoadGenePred -genePredExt malSym1 augustus augustus.genePredExt`, however I have no idea in which directory as I generally get `can't find database malGlo1 in hg.conf, should have a default named "db"`

**Comment by mrshu** [comment]
@Zygro just out of curiosity, did you follow this guide in order to set up your environment?

https://github.com/fmfi-genomika/genomika-2017/wiki/Basics-of-creating-tracks#getting-access-to-mysql

I guess it may help a bit =)

**Comment by Zygro** [comment]
done that, track is now online
