### ISSUE TITLE
(I) Genomes for comparative genomics (fast, only one group)

### ISSUE THREAD

**Issue by mrshu** [fmfi-genomika/genomikaMalGlo#9]
- Download genomes of additional Malassezia species (other than malGlo and malSym)
- Use list here [[3]](https://www.ncbi.nlm.nih.gov/genome/?term=txid55193%5BOrganism%3Aexp%5D), download M. pachydermatis, M. nana, M. equina, M. caprae, M. dermatis, M. restricta
  - Download one representative assembly per species (some species have multipe strains /assemblies)
- Rename chromosomes similarly as in A, name fasta files in a systematic way (malPac1.fa etc.)
- Store files in a directory at genomika server
- Do not forget to note down in your documentation the URL of each downloaded fasta file.

**Comment by mrshu** [comment]
I did download the respective files, here are the endpoints/URLs:

- https://www.ncbi.nlm.nih.gov/genome/39880
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/278/385/GCF_001278385.1_MalaPachy/GCF_001278385.1_MalaPachy_genomic.fna.gz

- https://www.ncbi.nlm.nih.gov/genome/39879
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/600/835/GCA_001600835.1_JCM_12085_assembly_v001/GCA_001600835.1_JCM_12085_assembly_v001_genomic.fna.gz

- https://www.ncbi.nlm.nih.gov/genome/39874
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/264/685/GCA_001264685.1_ASM126468v1/GCA_001264685.1_ASM126468v1_genomic.fna.gz

- https://www.ncbi.nlm.nih.gov/genome/39872
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/264/625/GCA_001264625.1_ASM126462v1/GCA_001264625.1_ASM126462v1_genomic.fna.gz

- https://www.ncbi.nlm.nih.gov/genome/39873
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/600/775/GCA_001600775.1_JCM_11348_assembly_v001/GCA_001600775.1_JCM_11348_assembly_v001_genomic.fna.gz

- https://www.ncbi.nlm.nih.gov/genome/702
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/264/725/GCA_001264725.1_ASM126472v1/GCA_001264725.1_ASM126472v1_genomic.fna.gz

The data is in my home directory on the `genomika` server.

I am not sure what documentation format would be best suited for this, so I guess we can leave it in this comment for now.

**Comment by vidriduch** [comment]
@mrshu I believe on last session there was said something about keeping all the data file in specific data folder on genomika server. It is of course open to discusen if we want to follow this convention.

**Comment by mrshu** [comment]
@vidriduch let's do that. Do you happen to know which folder that would be?

**Comment by vidriduch** [comment]
@mrshu I believe there should be `/data/malGlo` folder already created.

**Comment by mrshu** [comment]
@vidriduch Thanks, I've copied the data there.

I am therefore closing this task as done.

**Comment by bbrejova** [comment]
I would suggest adding the documentation from this conversation (the list of downloaded files with URLs) to the documentation describing creation of the multiple sequence alignment (task J) so that we have a record from which genomes was the alignment created. Unfortunately this documentation does not exist yet on the wiki.

**Comment by mrshu** [comment]
@bbrejova thanks for the note, I did add a wiki page to the documentation with the list above.

You can find it here: https://github.com/fmfi-genomika/genomikaMalGlo/wiki/Multiple-whole-genome-alignment

**Comment by bbrejova** [comment]
Looks good.
